version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  test_db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    profiles:
      - test

  test_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - test_db
    environment:
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: test_db
      DB_PORT: 5432
      DB_NAME: test_db
    profiles:
      - test

volumes:
  postgres_data:
